name: Execute Reddit comments.

on:
  schedule:
    - cron: "30 13 * * *"
    - cron: "30 14 * * *"
    - cron: "30 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1' # install the python version needed

      - name: install python packages
        run: pip install logging praw python-dotenv

      - name: execute py script # run main.py
        run: |
          python main.py
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID}}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET}}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT}}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME}}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD}}

      - name: Pull latest changes from remote
        run: git pull origin main

      - name: commit files
        run: |
          git config user.name "jonasnatividad"
          git config user.email "jonas.natividad.ii@gmail.com"
          git add .
          git commit -m "Ran reddit_commenter bot." || echo "No changes to commit"
          git push origin main